package com.cocode.tmsmeasurement.viewmodel

import com.cocode.tmsmeasurement.MeasurementRecord
import com.cocode.tmsmeasurement.data.LegacyImporter
import com.cocode.tmsmeasurement.data.LegacySource
import com.cocode.tmsmeasurement.data.MeasurementRepository
import com.cocode.tmsmeasurement.data.MeasurementWriter
import com.cocode.tmsmeasurement.data.MigrationFlag
import com.cocode.tmsmeasurement.data.TreatmentRepository
import com.cocode.tmsmeasurement.data.local.MeasurementEntity
import com.cocode.tmsmeasurement.data.local.TreatmentEntity
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.TestScope

/**
 * Plain-JVM test doubles and data builders shared by [MeasurementControllerTest].
 *
 * No Android, no Room, no org.json — objects are constructed directly so the
 * suite runs on the JVM without an emulator or Robolectric.
 */

internal fun entity(id: String, name: String = "Client $id") = MeasurementEntity(
    id = id,
    clientName = name,
    tttCm = 36.0,
    niCm = 38.0,
    hcCm = 60.0,
    xCm = 6.92,
    yCm = 9.76,
    yAdjCm = 10.11,
    timestampMs = id.toLongOrNull() ?: 0L
)

internal fun treatment(
    id: Long = 0,
    measurementId: String,
    dateMs: Long = 1_700_000_000_000L
) = TreatmentEntity(
    id = id,
    measurementId = measurementId,
    dateMs = dateMs,
    intensityPctMt = 120.0,
    totalPulses = 3000
)

internal fun legacyRecord(id: String) = MeasurementRecord(
    id = id,
    clientName = "Legacy $id",
    tttCm = 35.0,
    niCm = 37.0,
    hcCm = 59.0,
    xCm = 6.8,
    yCm = 9.5,
    yAdjCm = 10.0,
    timestampMs = id.toLong()
)

/** Builds a controller wired to [repo] with import already done (flag set). */
internal fun controllerWith(repo: FakeRepository, scope: TestScope): MeasurementController {
    val dispatcher = StandardTestDispatcher(scope.testScheduler)
    val importer = LegacyImporter(FakeSource(emptyList()), repo, FakeFlag(initial = true))
    return MeasurementController(repo, importer, scope, dispatcher, repo)
}

internal class FakeSource(private val records: List<MeasurementRecord>) : LegacySource {
    override fun load(): List<MeasurementRecord> = records
}

internal class FakeFlag(initial: Boolean = false) : MigrationFlag {
    private var done = initial
    override fun isDone() = done
    override fun markDone() { done = true }
}

internal class FakeRepository(seed: List<MeasurementEntity> = emptyList()) :
    MeasurementRepository, MeasurementWriter, TreatmentRepository {
    val state = MutableStateFlow(seed)
    val inserted = mutableListOf<MeasurementEntity>()
    val deleted = mutableListOf<String>()

    // Treatments keyed by autogenerated id; a StateFlow models Room's observable query.
    private var nextId = 1L
    val treatments = MutableStateFlow<List<TreatmentEntity>>(emptyList())
    val savedTreatments = mutableListOf<TreatmentEntity>()
    val deletedTreatments = mutableListOf<TreatmentEntity>()

    override fun observeMeasurements(): Flow<List<MeasurementEntity>> = state

    override suspend fun addMeasurement(entity: MeasurementEntity) {
        inserted += entity
        state.update { current -> listOf(entity) + current.filterNot { it.id == entity.id } }
    }

    override suspend fun deleteMeasurement(id: String) {
        deleted += id
        state.update { current -> current.filterNot { it.id == id } }
        // Mirror the Room foreign-key ON DELETE CASCADE.
        treatments.update { current -> current.filterNot { it.measurementId == id } }
    }

    override suspend fun insertAllIfAbsent(items: List<MeasurementEntity>) {
        items.forEach { entity ->
            if (state.value.none { it.id == entity.id }) {
                inserted += entity
                state.update { current -> listOf(entity) + current }
            }
        }
    }

    override suspend fun count(): Int = state.value.size

    override fun observeTreatments(measurementId: String): Flow<List<TreatmentEntity>> =
        treatments.map { all -> all.filter { it.measurementId == measurementId } }

    override suspend fun saveTreatment(entity: TreatmentEntity) {
        // Upsert: assign an id when new (id == 0), otherwise replace in place.
        val stored = if (entity.id == 0L) entity.copy(id = nextId++) else entity
        savedTreatments += stored
        treatments.update { current -> current.filterNot { it.id == stored.id } + stored }
    }

    override suspend fun deleteTreatment(entity: TreatmentEntity) {
        deletedTreatments += entity
        treatments.update { current -> current.filterNot { it.id == entity.id } }
    }

    override suspend fun getTreatment(id: Long): TreatmentEntity? =
        treatments.value.firstOrNull { it.id == id }
}
